# Generated by Django 5.2.1 on 2025-06-17 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(max_length=50, unique=True)),
                ('status_name', models.CharField(max_length=100)),
                ('is_agent_approval', models.BooleanField(default=False, help_text='Apakah status ini memerlukan persetujuan?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Platform',
                'verbose_name_plural': 'Attendance Platforms',
                'db_table': 'Attendance_Platform',
            },
        ),
        migrations.CreateModel(
            name='AbsenceRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('approval_timestamp', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_user', models.ForeignKey(blank=True, help_text='User yang menyetujui (atasan/admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absence_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('requester_user', models.ForeignKey(help_text='User yang mengajukan izin (Siswa/Guru/Staff)', on_delete=django.db.models.deletion.CASCADE, related_name='absence_requests_made', to=settings.AUTH_USER_MODEL)),
                ('absence_type_status', models.ForeignKey(help_text='Jenis izin, FK ke Attendance_Platform (misal: Sakit, Izin, Cuti)', on_delete=django.db.models.deletion.RESTRICT, to='attendance.attendanceplatform')),
            ],
            options={
                'verbose_name': 'Absence Request',
                'verbose_name_plural': 'Absence Requests',
                'db_table': 'Absence_Requests',
            },
        ),
        migrations.CreateModel(
            name='AbsenceRequestsAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(max_length=255)),
                ('file_name_original', models.CharField(blank=True, max_length=255, null=True)),
                ('file_mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size_bytes', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('absence_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='attendance.absencerequests')),
            ],
            options={
                'verbose_name': 'Absence Request Attachment',
                'verbose_name_plural': 'Absence Request Attachments',
                'db_table': 'Absence_Requests_Attachments',
            },
        ),
        migrations.CreateModel(
            name='SchoolHolidaysOrEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_date_start', models.DateField()),
                ('event_date_end', models.DateField()),
                ('is_school_off', models.BooleanField(default=False, help_text='Apakah pada hari ini sekolah libur?')),
                ('target_audience_type', models.CharField(choices=[('Students_Only', 'Students Only'), ('Teachers_Only', 'Teachers Only'), ('All_Users', 'All Users')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.academicyear')),
            ],
            options={
                'verbose_name': 'School Holiday or Event',
                'verbose_name_plural': 'School Holidays or Events',
                'db_table': 'School_Holidays_Or_Events',
            },
        ),
        migrations.CreateModel(
            name='Attendances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('clock_in_time', models.TimeField(blank=True, null=True)),
                ('clock_out_time', models.TimeField(blank=True, null=True)),
                ('clock_in_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('clock_in_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('clock_in_photo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('clock_out_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('clock_out_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('clock_out_photo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachment_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('absence_request', models.ForeignKey(blank=True, help_text='Jika absensi ini terkait dengan permintaan izin, FK ke Absence_Requests', null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.absencerequests')),
                ('attendance_status', models.ForeignKey(help_text='Status kehadiran, FK ke Attendance_Platform', on_delete=django.db.models.deletion.RESTRICT, to='attendance.attendanceplatform')),
                ('employee_user', models.ForeignKey(help_text='User yang melakukan absensi (Guru/Staff)', on_delete=django.db.models.deletion.CASCADE, related_name='attendances_taken', to=settings.AUTH_USER_MODEL)),
                ('recorded_by_user', models.ForeignKey(blank=True, help_text='User yang mencatat absensi ini jika dilakukan manual oleh admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances_recorded', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, help_text='Jika hari ini adalah event/libur, FK ke School_Holidays_Or_Events', null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.schoolholidaysorevents')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'db_table': 'Attendances',
            },
        ),
    ]
